### ISSUE TITLE
有关使用方法

### ISSUE THREAD

**Issue by Z735803792** [Todysheep/nonebot_plugin_bottle#1]
如何扔漂流瓶？私聊或者群里发送都没有回应
![image](https://user-images.githubusercontent.com/70925546/191147318-4029da03-12e4-4a9e-a7bc-af74fb3d3e04.png)

**Comment by Z735803792** [comment]
可以捡漂流瓶，但不能扔
![image](https://user-images.githubusercontent.com/70925546/191151940-d0bf0f3a-bbd0-40a0-84fa-07b2fc9ecf2e.png)

**Comment by Todysheep** [comment]
插件使用的是 `on_command` 命令触发方式，前边应该带命令前缀（具体配置在`.env`中`COMMAND_START`），如：
/扔漂流瓶 [内容/图片]
注意：图片触发方式为 `/扔漂流瓶 [图片]` (中间存在空格)
而不是：`/扔漂流瓶[图片]`

**Comment by Todysheep** [comment]
这是一个逻辑bug，将在下一个版本修复

**Comment by Todysheep** [comment]
更新完成，可使用pip或nb下载0.1.4版本
