### ISSUE TITLE
使用删除漂流瓶指令删除指定漂流瓶之后还是能捡到

### ISSUE THREAD

**Issue by AvastMEMZ** [Todysheep/nonebot_plugin_bottle#11]
如题，删除指定编号的漂流瓶之后使用捡漂流瓶指令还是能捡到，请问是特性还是bug。

**Comment by Todysheep** [comment]
此为bug，已经被修复，请在github下载最新`data_source.py`覆盖源文件即可

**Comment by AvastMEMZ** [comment]
> 此为bug，已经被修复，请在github下载最新`data_source.py`覆盖源文件即可

好的，感谢。
