### ISSUE TITLE
求救

### ISSUE THREAD

**Issue by dabao52099** [Todysheep/nonebot_plugin_bottle#12]
![Snipaste_2022-12-26_10-08-09](https://user-images.githubusercontent.com/108607907/209490335-d76f0200-808f-4f3f-b344-a1b21cee3bd3.png)
作者大哥 这报错怎么解决

**Comment by Todysheep** [comment]
你貌似更改了代码，因为我在对应行没有找到对应代码，你是想在回复功能也添加一个审核功能吗？

**Comment by Todysheep** [comment]
问题已经修复！原因是因为你使用的为其他人贡献的多机器人版本的代码，此版本存在bug，请更新至`0.1.8`版本(`main`分支)
