### ISSUE TITLE
能否出删除评论的功能

### ISSUE THREAD

**Issue by TNTobsidian** [Todysheep/nonebot_plugin_bottle#15]
有一些评论有问题，在data.json里删除有点麻烦😂能否出一个删除评论的功能呢，感谢！

**Comment by TNTobsidian** [comment]
还有就是能不能把评论的人的QQ也记下来啊🤔好拉黑名单（）

**Comment by Todysheep** [comment]
删除功能已经实现，请详细查看`README.md`
关于个人QQ屏蔽，将在下一个版本实现

**Comment by TNTobsidian** [comment]
> 

是指漂流瓶下的评论，不是漂流瓶本身(´･Д･)」

**Comment by Todysheep** [comment]
了解，会在下一个版本更新，由于需要更改data.json的数据结构，要做一些兼容，所以需要些时间更新

**Comment by TNTobsidian** [comment]
> 了解，会在下一个版本更新，由于需要更改data.json的数据结构，要做一些兼容，所以需要些时间更新

好的好的！感谢🙏🥰

**Comment by Todysheep** [comment]
黑名单功能、删除评论功能均已更新`0.2.1`！
具体功能请查看README，感谢你的建议！
