### ISSUE TITLE
【功能建议】冷却功能

### ISSUE THREAD

**Issue by TNTobsidian** [Todysheep/nonebot_plugin_bottle#17]
可以设置在x秒内只能捡y个漂流瓶，超出限制就拒绝的那种嘛？至于实现方式目前有两个，一个是触发满了y次进入倒计时，一个是实时计算最近x秒内瓶子个数有没有超过y，怎么实现都可以（其实是我不知道哪个能实现hhh）主要是怕被风控（狗头
感谢！

**Comment by Todysheep** [comment]
感谢你的建议，功能已经更新！请查看`0.2.1`版本的README！
