### ISSUE TITLE
cd并没有作用

### ISSUE THREAD

**Issue by TNTobsidian** [Todysheep/nonebot_plugin_bottle#18]
如下图所示，两个信息之间间隔绝对小于6s，且机器人处于正常运行状态，无卡顿。并且，图示账号并非SUPERUSER（S），是我开的测试小号
![61CFC2CA-4A3E-4D50-B56D-0FF74EC9B7A1](https://user-images.githubusercontent.com/65720409/211055385-cb28f276-7580-48c4-956e-317a46436b48.jpeg)
配置文件：
![B599F33B-C3A1-4CF3-B9A7-27F456A5508C](https://user-images.githubusercontent.com/65720409/211055661-99be027d-bb06-440d-b9bf-bede8613fd58.jpeg)

**Comment by Todysheep** [comment]
感谢你详尽的问题描述，问题已经解决！是因为只实现了`扔漂流瓶`的CD添加功能而没有在其他指令上实现，请更新至`0.2.1.1`版本！
