### ISSUE TITLE
简单文字审核没有生效

### ISSUE THREAD

**Issue by TNTobsidian** [Todysheep/nonebot_plugin_bottle#20]
curse.json 文件如下
![image](https://user-images.githubusercontent.com/65720409/211509755-e1261736-6de6-4447-8a9c-829155756ef3.png)
在群内用非SUPERUSER扔瓶子截图：
![PNG image](https://user-images.githubusercontent.com/65720409/211510265-a7728d14-9fb4-4ce5-a5e3-be643282db1e.png)
bottle版本为nb脚手架获取的最新版本（我也忘了怎么看具体的版本是多少了）

**Comment by Todysheep** [comment]
感谢你的反馈！问题已经修复，请更新至`0.2.2.1`版本！

**Comment by TNTobsidian** [comment]
您确定修了吗QAQ我今天上午测试了一下还是不行
![14A72B35-74A3-48C2-B0D0-2D48D3F3C089](https://user-images.githubusercontent.com/65720409/211747703-5c937457-119a-4531-bebb-c23cf1cca43e.jpeg)
![30D7A812-2F66-45CB-8F9C-F9D1D5FC57D7](https://user-images.githubusercontent.com/65720409/211747739-12ad32ce-04e5-49fc-8a68-ce4cab6cb54f.jpeg)

**Comment by TNTobsidian** [comment]
您确定修了吗QAQ我今天上午测试了一下还是不行
![14A72B35-74A3-48C2-B0D0-2D48D3F3C089](https://user-images.githubusercontent.com/65720409/211747703-5c937457-119a-4531-bebb-c23cf1cca43e.jpeg)

**Comment by Todysheep** [comment]
有一个缩进错误，我自裁，请更新到`0.2.2.2`（
