### ISSUE TITLE
扔漂流瓶指令后跟着的文字会被忽略，而不是无视指令

### ISSUE THREAD

**Issue by TNTobsidian** [Todysheep/nonebot_plugin_bottle#21]
扔漂流瓶指令后跟着的文字会被忽略，而不是无视指令。也就是说，在输入命令 扔漂流瓶 之后，在这段文字后面不加空格，输入的内容全部作废，识别称为扔漂流瓶指令。正常的话，应该是指令只要不匹配扔漂流瓶这四个字就直接忽视吧（）
举个例子就是：
扔漂流瓶哈哈哈哈哈哈哈哈哈哈 会被识别成 扔漂流瓶
扔漂流瓶哈哈哈哈哈哈哈哈哈哈 呵呵呵 会被识别成 扔漂流瓶 呵呵呵
如果这是特性的话，当我没说（）

**Comment by Todysheep** [comment]
对的，代码中的逻辑是指令后应该加空格（使用.split方法），只会扔出空格后的所有内容，所以应该是要加空格的（

**Comment by Todysheep** [comment]
如果你不想打空格的话，你可以把代码中`split`方法改为`.replace("扔漂流瓶")`，这个是在没有`指令前缀`的情况下，如果需要前缀，自行添加就好

**Comment by Todysheep** [comment]
补充一下，指令方式是`扔漂流瓶 [文字/图片]`中间应用空格隔开
