### ISSUE TITLE
【建议】设置自己删除自己漂流瓶的权限

### ISSUE THREAD

**Issue by TNTobsidian** [Todysheep/nonebot_plugin_bottle#22]
可以出一个自己删除自己漂流瓶的功能（）最好删除前可以显示部分摘要二次确认（？）谢谢爆肝Tody大大！

**Comment by Todysheep** [comment]
感谢建议！功能已经更新，请更新至`0.2.3`版本！

**Comment by Todysheep** [comment]
另外显示摘要没有实现，还请使用`查看漂流瓶`指令（（

**Comment by TNTobsidian** [comment]
> 另外显示摘要没有实现，还请使用`查看漂流瓶`指令（（

超级感谢啦！！qwq
