### ISSUE TITLE
瓶子没有文字也能被扔出去

### ISSUE THREAD

**Issue by TNTobsidian** [Todysheep/nonebot_plugin_bottle#23]
如题，瓶子没有文字也能被扔出去，只要加了空格（？）这个能修吗（）
![EBDA3748-2B61-416F-AB96-30D860BFA8AF](https://user-images.githubusercontent.com/65720409/212802536-c14bbc11-6111-4e6a-bcdd-9a78d476ff23.jpeg)

**Comment by Todysheep** [comment]
感谢反馈，`0.2.3`版本已经要求有后续内容才能扔出！
