### ISSUE TITLE
瓶子不能只丢图片了（？）

### ISSUE THREAD

**Issue by TNTobsidian** [Todysheep/nonebot_plugin_bottle#24]
没错，我又来了！（）之前在 #23 被修复之前是可以瓶子里就跟着一个图片的，现在图片必须加文字了（悲）这个能看着修吗（）指令后面加空格了（
![B61D428A-C2C1-43C9-A8E9-6ED52DE6CBBE](https://user-images.githubusercontent.com/65720409/213109571-2149b9a7-f4c2-47e4-bead-1db760eb3e5c.jpeg)

**Comment by Todysheep** [comment]
修好了修好了，更新到`0.2.3.1`版本就好，但是即使只单扔一张图片指令后面的空格也要打的哦（
![image](https://user-images.githubusercontent.com/97968466/213113314-1e1698c9-9249-493a-8c8f-0b1b07f953bc.png)

**Comment by TNTobsidian** [comment]
> 修好了修好了，更新到`0.2.3.1`版本就好，但是即使只单扔一张图片指令后面的空格也要打的哦（
> ![image](https://user-images.githubusercontent.com/97968466/213113314-1e1698c9-9249-493a-8c8f-0b1b07f953bc.png)

嗯嗯！哈哈哈
