### ISSUE TITLE
功能建议：记录漂流瓶时间

### ISSUE THREAD

**Issue by Sevenyine** [Todysheep/nonebot_plugin_bottle#25]
建议记录一下扔漂流瓶的时间，方便后期人看这个瓶子的时效性（）感谢！

**Comment by Todysheep** [comment]
刚从学(jian)校(yu)回来，我马上更新（

**Comment by Todysheep** [comment]
更新完成了，可以使用查看漂流瓶指令查看时间，之前的瓶子因为没有记录，为了兼容全部都为`0000-00-00 00:00:00`
至于为什么不在`捡漂流瓶`的反馈文本中加入时间
~~别问我我看着排版太乱了不能再加了~~

**Comment by Sevenyine** [comment]
> 更新完成了，版本`0.2.4`。可以使用查看漂流瓶指令查看时间，之前的瓶子因为没有记录，为了兼容全部都为`0000-00-00 00:00:00`
> 至于为什么不在`捡漂流瓶`的反馈文本中加入时间
> ~别问我我看着排版太乱了不能再加了~

我觉得可以多用换行功能（其实是我从别的bot自己写的漂流瓶插件那里偷来的灵感）哈哈哈
而且有的时候时间对于判断漂流瓶内容的时效性有较大影响
当然还是以您的喜好为主，我看这样的格式可以更明确一些：
```
编号：编号
投掷人：昵称
投掷群：群名称
时间：xxx
内容：内容
```
可以删掉捡到次数的显示，在查看漂流瓶里面补上，在群聊中占据屏幕一半空间。
或者可以的话，格式化一下捡漂流瓶（如上）后开放选择性显示的功能（似乎有点麻烦）
您辛苦啦，以学习为主🥰
