### ISSUE TITLE
发现一个疑似违反GPLv3.0协议的项目

### ISSUE THREAD

**Issue by 34245621** [Todysheep/nonebot_plugin_bottle#26]
在网址 http://www.szkiiko.top/ 所描述的QQ机器人中使用了您的漂流瓶插件，通过他人得知，机器人（账号为“2438912171”）确实使用了您的漂流瓶插件，但是疑似未遵守GPLv3.0协议。
故在此转告。

**Comment by Todysheep** [comment]
感谢你的反馈，但是你可以详细告诉我一下他违反了哪一条协议吗
