### ISSUE TITLE
较严重bug：同一个人可以多次举报漂流瓶

### ISSUE THREAD

**Issue by Sevenyine** [Todysheep/nonebot_plugin_bottle#28]
如题：同一个人可以通过多次举报漂流瓶的方式来删除漂流瓶，影响较为严重。建议漂流瓶json通过记录举报人qq号的方式避免重复举报
![80FB66C3-4AFA-4F98-BF4F-D7B6568FF545](https://user-images.githubusercontent.com/65720409/217252862-123d8e7d-75e9-408e-b618-32c984802055.jpeg)

**Comment by Sevenyine** [comment]
PS：如果作者有时间 能否在此改动后加上恢复某个漂流瓶的封禁功能和删除某用户在所有漂流瓶下的举报功能呢（防止恶意举报）？感谢😂🥰🥰

**Comment by Sevenyine** [comment]
> 抱歉这么晚处理issue（被学校关住了（不是
> 关于 同一个人可以举报多次漂流瓶 的问题已经修复`0.2.6版本`（其实一开始写举报功能的时候我就想到了，~是故意的还是不小心的~）
> 关于你提到的 恢复某个漂流瓶的封禁功能 我没有明白你表达的意思，可以再说一下吗（

感谢修复！哈哈哈我也猜到了被学校关起来但是没想到这次关了这么久
恢复封禁就是比如遇到了恶意举报，然后给主人发消息后我发现这个瓶子没问题想取消封禁（）这种

**Comment by Todysheep** [comment]
所有功能都已经实现了，还请更新至`0.2.7`版本！感谢建议！
接下来就是回学校接受一个月的~~有期徒刑~~

**Comment by Sevenyine** [comment]
> 所有功能都已经实现了，还请更新至`0.2.7`版本！感谢建议！
> 接下来就是回学校接受一个月的~有期徒刑~

原来是一个月吗（泪）您加油
