### ISSUE TITLE
漂流瓶，扔漂流瓶的命令不生效。可以加个联系方式询问一下吗

### ISSUE THREAD

**Issue by LSGLSH** [Todysheep/nonebot_plugin_bottle#3]
![Screenshot_2022-09-20-17-33-03-385_com tencent tim](https://user-images.githubusercontent.com/106002475/191223237-428b2161-d91e-4cc1-9904-302962061c20.jpg)

**Comment by Todysheep** [comment]
请更新至 v0.1.4 后重试
`pip install nonebot-plugin-bottle==0.1.4`

**Comment by LSGLSH** [comment]
> 请更新至 v0.1.4 后重试 `pip install nonebot-plugin-bottle==0.1.4`

我是今天五点下载的文件，应该是最新版本，命令不生效也没有报错

**Comment by Todysheep** [comment]
麻烦运行`pip list` 查看下 `nonebot_plugin_bottle`版本号

**Comment by LSGLSH** [comment]
> 麻烦运行`pip list` 查看下 `nonebot_plugin_bottle`版本号

确定了是0.1.4

**Comment by Todysheep** [comment]
如果是第一次启动会存在无法使用的问题，可以尝试重启bot.py

**Comment by LSGLSH** [comment]
> 如果是第一次启动会存在无法使用的问题，可以尝试重启bot.py

重启很多次，只有扔漂流瓶的命令无法生效

**Comment by LSGLSH** [comment]
> 如果是第一次启动会存在无法使用的问题，可以尝试重启bot.py

问题找到了，是和头像表情包命令冲突，部分安装头像表情包插件的用户，使用这个插件，扔漂流瓶这个命令会和头像表情包扔这个命令冲突，可以考虑修改成寄漂流瓶。

**Comment by Todysheep** [comment]
了解，感谢反馈，将在下一个版本修复

**Comment by LSGLSH** [comment]
> 了解，感谢反馈，将在下一个版本修复

谢谢大佬，大佬辛苦了
