### ISSUE TITLE
【功能建议】将漂流瓶的图片保存到本地

### ISSUE THREAD

**Issue by Sevenyine** [Todysheep/nonebot_plugin_bottle#30]
如题，由于SM藤蕈会让图片链接失效，直接记录用户扔出去的CQ码会导致如果本地没有缓存，其他人那边看到的图片是失效的缩略图，点不开（）希望能够通过保存用户扔的图片到本地，并且每次发送时调用本地对应的漂流瓶编号图片的文件来解决（）
但不过这样会增加本地使用内存，所以其他用户可以通过开关来设置是否保存（雾）感谢！

**Comment by Sevenyine** [comment]
经过我的测试，发现原图会被清理，无论原图大小（测试了不到非原图、1MB，1MB-2MB，5MB+四个档位，除了第一个全部失效）都会被清理导致其他人无法看见。希望能够在发送原图的时候保存非原图或者通过保存图片到本地防止图片失效。我可能不太懂 不过我看nonebot 有一个类似的插件（）[nonebot_plugin_cave](https://github.com/hmzz804/nonebot_plugin_cave)，其中用的应该就是本地保存策略🥰感谢！

**Comment by Todysheep** [comment]
泻药，刚从学校回来，已经发现有带佬帮我写好了，我先谢罪（

**Comment by Sevenyine** [comment]
哦对 给后来的人提示一下 如果图片太多，机器人会发一堆空瓶子，可以用正则表达式清除这些内容。
首先，用`[CQ:image,file=[\S]*,subType=[\S]*,url=[\S]*\]`匹配图片，并全部替换为空
其次，用这个表达式删除所有空瓶子：```
"del": 0,
        "user": [\S]*,
        "group": [\S]*,
        "user_name": "[\S]*\s+[\S]*",
        "group_name": "[\S]*\s+[\S]*",
        "text": "",
        "report": [\S]*,
        "reported": [\S]*,
        "picked": [\S]*,
        "comment": [\S]*
        "time": "[\S]* [\S]*"
```
最后，用这个表达式清除剩下的大括号：`^\s*\{\s*\}\s*,$`
这样就没有图片瓶子啦。
如果有更简单的表达式欢迎指出（）
