### ISSUE TITLE
【Bug】重构版旧数据导入不支持旧日期

### ISSUE THREAD

**Issue by Sevenyine** [Todysheep/nonebot_plugin_bottle#37]
如题，当迁移遇到旧的漂流瓶的默认日期0000-00-00时会出现迁移错误，并无法迁移任何数据。
`04-30 16:31:17 [ERROR] nonebot_plugin_datastore | 数据库初始化后执行的函数出错: time data '0000-00-00 00:00:00' does not match format '%Y-%m-%d %H:%M:%`
![A5FADD64-ED85-4721-9535-F968A7820B62](https://user-images.githubusercontent.com/65720409/235343957-564eb92b-4581-4a61-97cf-fa6bc9dd63b2.jpeg)

**Comment by LambdaYH** [comment]
因为对旧数据不怎么熟悉所以写的时候比较偷懒（

**Comment by Sevenyine** [comment]
> 因为对旧数据不怎么熟悉所以写的时候比较偷懒（

其实如果不想修我可以把所有0000-00-00改成1980-01-01 不过能修最好（

**Comment by LambdaYH** [comment]
https://github.com/Todysheep/nonebot_plugin_bottle/commit/957eef6a2248798a53455415aef05df832be261c

**Comment by Sevenyine** [comment]
好的我改完了

> [957eef6](https://github.com/Todysheep/nonebot_plugin_bottle/commit/957eef6a2248798a53455415aef05df832be261c)
> 应该好了，理论上

好 我改成1970了（）就不测试了哈哈哈
