### ISSUE TITLE
【Bug】捡漂流瓶昵称错误

### ISSUE THREAD

**Issue by Sevenyine** [Todysheep/nonebot_plugin_bottle#40]
Bug描述：如题，经过测试，捡漂流瓶、查看漂流瓶的时候，都将读取当前执行命令的人作为扔漂流瓶的对象，以及会将当前执行群作为扔出的群。这个bug不影响数据存储。
错误原因：在`@get.handle` 和 `@check_bottle.handle`中，将`bottle.user_id`和`bottle.group_id`写为`event.user_id`和`event.group_id`。（是不是复制的时候忘改了）
PR：已创建 #41 
附bug截图（最后一条消息是修改后的）
![D2EA0F07-EE49-45A2-834F-FC2FB8EB3A98](https://github.com/Todysheep/nonebot_plugin_bottle/assets/65720409/d3ca88e0-c7ca-423c-888c-2b2d19b9a8a2)

**Comment by LambdaYH** [comment]
吃下了顺便pypi发布了1.0.0.5
