### ISSUE TITLE
关于评论通知问题

### ISSUE THREAD

**Issue by LSGLSH** [Todysheep/nonebot_plugin_bottle#5]
可以考虑采用群艾特，某人在某个群发的漂流瓶，别人评论直接在发漂流瓶的群艾特发漂流瓶的人通知回复，因为不是所有人都有机器人好友。这样就方便许多，也避免了私聊风控的风险。

**Comment by Todysheep** [comment]
了解，感谢反馈，你的建议将在下个版本更新
