### ISSUE TITLE
该消息类型暂不支持查看

### ISSUE THREAD

**Issue by axlmly** [Todysheep/nonebot_plugin_bottle#51]
开启冷却情况下，在未结束冷却时会发送标题文段。
09-02 06:04:25 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_bottle)

09-02 06:04:25 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_bottle) running complete

注，用的外置的gocq，白名单成员与关闭冷却后未出现

**Comment by Sevenyine** [comment]
有无gocq端日志

**Comment by LambdaYH** [comment]
标题文段，是指哪个

**Comment by LambdaYH** [comment]
`permissionList.json`里面的`bannedMessage`有写什么吗

**Comment by LambdaYH** [comment]
> `permissionList.json`里面的`bannedMessage`有写什么吗

我也复现了

**Comment by LambdaYH** [comment]
逝世新版

**Comment by Sevenyine** [comment]
> 逝世新版

提示信息怎么又回去了（？）
![IMG_4376](https://github.com/Todysheep/nonebot_plugin_bottle/assets/65720409/5b6b338f-3a24-4400-b49b-7bb9a41d91d7)

**Comment by LambdaYH** [comment]
> > 逝世新版
> 
> 提示信息怎么又回去了（？） ![IMG_4376](https://user-images.githubusercontent.com/65720409/265174602-5b6b338f-3a24-4400-b49b-7bb9a41d91d7.jpeg)

在后面一个commit又改回来了（
