### ISSUE TITLE
关于点赞功能

### ISSUE THREAD

**Issue by Sevenyine** [Todysheep/nonebot_plugin_bottle#57]
想写一个点赞的功能，为了方便用户点赞（不然谁还输入那么长的指令啊，笑死）我想的是在获取玩漂流瓶后，用户发送“+”就可以直接点赞。
初步想的是在get.handle后通过get.got获取下一步消息，并且只监听最近的一条消息。
其他的都写好了，问题出在如何精准获取get.handle后的bottle id。如果用T_state把id保存到一个key 中，那么假设有一个时间差：
A在群聊a中get了一次，然后B在群聊b中get了一次，此时A发送+，获取到的就是B的bottleid了。
🤔非常坏功能，这样我本就不聪明的脑子失败运作。
除了这上面的这个功能 其他的我尝试着写了一下（）如果大大有意向完善这个功能的话感激不尽！没有的话就close掉(^з^)-☆
https://github.com/Sevenyine/nonebot_plugin_bottle/commit/7c93a9ab726a369ccadca9a9a37f81eb8f2db713

**Comment by LambdaYH** [comment]
T_State应该是只保存当前会话的信息啊，b再群聊里说话不会干扰a

**Comment by Sevenyine** [comment]
> T_State应该是只保存当前会话的信息啊，b再群聊里说话不会干扰a

诶 我可能举错例子了，应该是B也在a群里获取（）

**Comment by LambdaYH** [comment]
你先提个pr，我push过来

**Comment by Sevenyine** [comment]
要改的多了，~~我全是抄的~~
