### ISSUE TITLE
多账号的情况下提示群聊不存在

### ISSUE THREAD

**Issue by MTmin** [Todysheep/nonebot_plugin_bottle#6]
多账号的情况下提示群聊不存在

**Comment by Todysheep** [comment]
这是因为显示群聊名称方法为通过cq-http API获取，若机器人未加入群聊则无法获取
将在下个版本被修复，在json文件夹中加入group_name与user_name

**Comment by MTmin** [comment]
> 这是因为显示群聊名称方法为通过cq-http API获取，若机器人未加入群聊则无法获取 将在下个版本被修复，在json文件夹中加入group_name与user_name

您好,这个问题需要记录机器人的QQ,获取名称的时候用记录的QQ去获取就好了,还有回复的时候

**Comment by Todysheep** [comment]
这个问题已经被修复，请更新插件至最新版本(0.1.7)
因缺少测试，如有问题请及时反馈

**Comment by MTmin** [comment]
> 这个问题已经被修复，请更新插件至最新版本(0.1.7) 已经存在的漂流瓶无法获取名称，将被替换为群号/qq号，后续的漂流瓶不受影响 因缺少测试，如有问题请及时反馈

您好,还是要记录个机器人QQ,不然回复的时候无法回复....

**Comment by MTmin** [comment]
> 我这里测试没有问题，请核对一下问题：
> 
> * 核对插件版本为 0.1.7
> * 核对该漂流瓶存在
>   如果核对完成后还存在问题，请将报错、机器人返回消息截图给我

原因是因为,回复的时候没有回复的那个推送,因为丢瓶子的机器人是一个,捡瓶子的机器人是一个,所以无法推送回复,我给他改了下,已经提交了pr了,版本是0.1.7
