### ISSUE TITLE
点赞功能bug

### ISSUE THREAD

**Issue by Sevenyine** [Todysheep/nonebot_plugin_bottle#60]
今天通过+快速点赞的时候发现有的时候点不上，想了一下应该是这个原因。
第`2n (n \in Z)`次捡漂流瓶（此时触发got），第`2n+1`次也捡漂流瓶（此时got结束，block设置为False就没有got了）
第`2n+2`次输入+就不会有反应了

**Comment by Sevenyine** [comment]
![IMG_5309](https://github.com/Todysheep/nonebot_plugin_bottle/assets/65720409/e8c03d72-9969-451d-8051-7eb9e879ade8)

**Comment by LambdaYH** [comment]
虽然有办法替代block，但是block应该只影响事件传递，不会阻碍事件的触发

（有日志吗

**Comment by Sevenyine** [comment]
`2n`
11-06 19:30:06[SUCCESS] nonebot| OneBot V11| [message.group.normal]: Message 2078710274 From@[群:] '.捡漂流瓶'
11-06 19:30:06[INFO] nonebot| Event will be handled by Matcher(type='message', module=nonebot_plugin_admin.word_analyze, lineno=56)
11-06 19:30:06[INFO] nonebot| Matcher(type='message', module=nonebot_plugin_admin.word_analyze, lineno=56) running complete
11-06 19:30:06[INFO] nonebot| Event will be handled by Matcher(type='message', module=nonebot_plugin_admin.auto_ban, lineno=18)
11-06 19:30:06[INFO] nonebot| Event will be handled by Matcher(type='message', module=nonebot_plugin_admin.img_check, lineno=16)
11-06 19:30:06[INFO] nonebot| Matcher(type='message', module=nonebot_plugin_admin.auto_ban, lineno=18) running is cancelled
11-06 19:30:06[INFO] nonebot| Matcher(type='message', module=nonebot_plugin_admin.img_check, lineno=16) running is cancelled
11-06 19:30:07[INFO] nonebot| Event will be handled by Matcher(type='message', module=nonebot_plugin_bottle, lineno=72)
`2n+1`
11-06 19:30:45[SUCCESS] nonebot| OneBot V11| [message.group.normal]: Message -1836761289 from@[群:] '.捡漂流瓶'
11-06 19:30:45[INFO] nonebot| Event will be handled by Matcher(type='message', module=nonebot_plugin_bottle, lineno=72)
11-06 19:30:45[INFO] nonebot| Matcher(type='message', module=nonebot_plugin_bottle, lineno=72) running complete
11-06 19:30:45[INFO] nonebot| Event will be handled by Matcher(type='message', module=nonebot_plugin_admin.word_analyze, lineno=56)
11-06 19:30:45[INFO] nonebot| Matcher(type='message', module=nonebot_plugin_admin.word_analyze, lineno=56) running complete
11-06 19:30:45[INFO] nonebot| Event will be handled by Matcher(type='message', module=nonebot_plugin_admin.auto_ban, lineno=18)
11-06 19:30:45[INFO] nonebot| Event will be handled by Matcher(type='message', module=nonebot_plugin_admin.img_check, lineno=16)
11-06 19:30:45[INFO] nonebot| Matcher(type='message', module=nonebot_plugin_admin.auto_ban, lineno=18) running is cancelled
11-06 19:30:45[INFO] nonebot| Matcher(type='message', module=nonebot_plugin_admin.img_check, lineno=16) running is cancelled
11-06 19:30:45[INFO] nonebot| Event will be handled by Matcher(type='message', module=nonebot_plugin_bottle, lineno=72)
11-06 19:30:47[INFO] nonebot| Matcher(type='message', module=nonebot_plugin_bottle, lineno=72) running complete
`2n+2`
11-06 19:31:09[SUCCESS] nonebot| OneBot V11| [message.group.normal]: Message 2089508379 from@[群:] '+'
11-06 19:31:09[INFO] nonebot| Event will be handled by Matcher(type='message', module=nonebot_plugin_admin.word_analyze, lineno=56)
11-06 19:31:09[INFO] nonebot| Matcher(type='message', module=nonebot_plugin_admin.word_analyze, lineno=56) running complete
11-06 19:31:09[INFO] nonebot| Event will be handled by Matcher(type='message', module=nonebot_plugin_admin.auto_ban, lineno=18)
11-06 19:31:09[INFO] nonebot| Event will be handled by Matcher(type='message', module=nonebot_plugin_admin.img_check, lineno=16)
11-06 19:31:09[INFO] nonebot| Matcher(type='message', module=nonebot_plugin_admin.auto_ban, lineno=18) running is cancelled
11-06 19:31:09[INFO] nonebot| Matcher(type='message', module=nonebot_plugin_admin.img_check, lineno=16) running is cancelled

**Comment by Sevenyine** [comment]
2n+1次它直接就running complete了而没有留到下一次

**Comment by Sevenyine** [comment]
> 试试新版，这种就是会导致日志里出现同消息的两个响应

修复啦
能用就行（？）日志什么的 反正后台已经够乱了
