### ISSUE TITLE
[feature request] 通过加可选参数的方法，实现“评论漂流瓶时不发送提示”

### ISSUE THREAD

**Issue by ajchen02** [Todysheep/nonebot_plugin_bottle#64]
如题（
主要是有些时候回复刷屏了有点尴尬（

俺的主意是（在回复的时候）加个 -noping 啥的

**Comment by LambdaYH** [comment]
回复  具体是哪种情况（

**Comment by ajchen02** [comment]
啊我打错字了
是`/评论漂流瓶`（绝望

**Comment by LambdaYH** [comment]
是指评论成功后回复的“回复成功！”吗。

我添加个配置项关闭这个回复可以吗，还是说需要临时关闭。

**Comment by ajchen02** [comment]
不是“回复成功”，是“你的漂流瓶被回应啦”那个提示
主要是我这群比较多，有时候会出现 群里聊着聊着 bot突然出来大喊一句“你的漂流瓶被回应啦”（
如果能选择评论漂流瓶不反馈提示的话可能会好很多

**Comment by LambdaYH** [comment]
那我加个配置项，可以通过配置关闭这个提示

**Comment by LambdaYH** [comment]
试试新版

`.env.xxx`文件中添加`nonebot_plugin_bottle_disable_comment_prompt = True`可以关闭被评论时候的提示

**Comment by ajchen02** [comment]
thx
虽然我已经用暴力注释解决了（

**Comment by ajchen02** [comment]
那来都来了，要不把`/查看漂流瓶`的权限也改成配置项（、

**Comment by LambdaYH** [comment]
可配置成所有人都能查看？

**Comment by ajchen02** [comment]
对（

**Comment by ajchen02** [comment]
![image](https://github.com/Todysheep/nonebot_plugin_bottle/assets/88434425/a845f455-1697-4a60-b63e-aa0fd858992d)
uh
