### ISSUE TITLE
[feature request]`/漂流瓶详情` 显示更多信息 （是否被删除，举报次数，举报人）

### ISSUE THREAD

**Issue by ajchen02** [Todysheep/nonebot_plugin_bottle#65]

**Comment by LambdaYH** [comment]
最近事情有点多，有空一定改（

**Comment by ajchen02** [comment]
草，竟然改成转发了
那我这测试不了了，[lagrange的转发消息好像不太一样](https://lagrangedev.github.io/Lagrange.Doc/Lagrange.OneBot/API/Extend/)

**Comment by LambdaYH** [comment]
https://github.com/Todysheep/nonebot_plugin_bottle/commit/8643a5209ccfee1a762a6977d07e1393fe877670

没怎么仔细测过，应该能用

**Comment by ajchen02** [comment]
感谢

**Comment by ajchen02** [comment]
我主要是换[LLOneBot](https://github.com/LLOneBot/LLOneBot)了
这个 压 根 就[不支持伪造转发聊天](https://github.com/LLOneBot/LLOneBot/issues/119)
也不麻烦大佬再整了

**Comment by LambdaYH** [comment]
发送转发消息时候会报错还是发送空消息？如果会报错的话我可以改成转发失败后逐条发送

**Comment by ajchen02** [comment]
...我今天才发现，竟然会正常发出来？？？
![image](https://github.com/Todysheep/nonebot_plugin_bottle/assets/88434425/8d409f29-2425-4087-8764-74041a3b57ab)
...但是我感觉逐条发送可能会更安全一点，要不改成设置项啥的吧

**Comment by ajchen02** [comment]
他实际上是先发给了自己，然后再把自己的消息记录转发出去了
不知道这是怎么实现的说实话，但至少是能用

**Comment by LambdaYH** [comment]
逐条容易风控（，不过确实可以加个配置项关闭转发

**Comment by LambdaYH** [comment]
试试新版（没测试过

**Comment by ajchen02** [comment]
现在看着没问题（
辛苦佬改来改去了
