### ISSUE TITLE
【功能请求】遍历漂流瓶

### ISSUE THREAD

**Issue by Xian0Grem** [Todysheep/nonebot_plugin_bottle#69]
想要一个 私聊可以遍历自己的漂流瓶，正常查 我的漂流瓶 的图片是被折叠的

此功能最大的意义是可以自查自己的漂流瓶，有时候qq会吞图片 但是漂流瓶还是扔出去了 这时候就会出问题

**Comment by Sevenyine** [comment]
如果被吞图片了 自己想检查图片有没有正常被丢出的话 可以根据bot给的漂流瓶id自行通过 `/查看漂流瓶` 或 `/漂流瓶详情` 查看，如果是空瓶子可以删除。
当时折叠图片是怕有人丢了太多图片然后遍历，服务器流量直接炸了
