### ISSUE TITLE
Action无法发布到Pypi啦 :ice_cube:

### ISSUE THREAD

**Issue by LambdaYH** [Todysheep/nonebot_plugin_bottle#73]
@Todysheep 
```
HTTP Error 400: User 'todysheep' does not have a verified primary email address. Please add a verified primary email before attempting to upload to PyPI. See https://pypi.org/help/#verified-email for more information.
```

**Comment by Sevenyine** [comment]
估计6月10日准时复活.jpg

**Comment by Todysheep** [comment]
![image](https://github.com/Todysheep/nonebot_plugin_bottle/assets/97968466/f40104f1-c6f6-4a7a-bd6b-fe48f1bc3b17)
可能……验证成功了？
~~到处乱玩没看GitHub抱歉喵（~~

**Comment by LambdaYH** [comment]
叒发布不了了，`HTTP Error 400: User 'todysheep' does not have two-factor authentication enabled. ` 应该是要开启二次验证
@Todysheep

**Comment by Sevenyine** [comment]
噫（）tody还没回来嘛 @Todysheep

**Comment by Todysheep** [comment]
诶，我应该加上了啊（

**Comment by LambdaYH** [comment]
确实可以了（

**Comment by Sevenyine** [comment]
（突然想起来翻这个仓库然后看到这个issue竟然还开着（什么

**Comment by Todysheep** [comment]
我会努力学Python争取在这个仓库再创一commit的（？）
