### ISSUE TITLE
TypeError: argument of type 'bool' is not iterable报错，但是不知道怎么结局，求大佬解答

### ISSUE THREAD

**Issue by Momoi-coder** [Todysheep/nonebot_plugin_bottle#76]
<img width="916" alt="A2A34BCC634940D2D2E4F47E605D22D0" src="https://github.com/Todysheep/nonebot_plugin_bottle/assets/172282304/53b2de82-7460-4cdc-a386-3c3bb0aa8930">

**Comment by LambdaYH** [comment]
看看配置文件，估计里面改错了

**Comment by Momoi-coder** [comment]
<img width="1150" alt="3B5E05841DFE25799F7849D0996CB7A2" src="https://github.com/Todysheep/nonebot_plugin_bottle/assets/172282304/523d373a-ee69-4efd-bbe2-d5d205658544">
da'la
<img width="538" alt="777DCB2A2535EEDB348800D84669B99D" src="https://github.com/Todysheep/nonebot_plugin_bottle/assets/172282304/e4ba0514-3ab2-4987-a534-257a611cd600">
大佬您好，我是这样配置的，但是一直报错

**Comment by Momoi-coder** [comment]
<img width="1154" alt="6B98928AE8D82831F3F4851A3614D25B" src="https://github.com/Todysheep/nonebot_plugin_bottle/assets/172282304/77012228-6d17-4087-90ca-361650f384b6">
<img width="1139" alt="22FCCFBF041CC9037835E5E32C3DC9A6" src="https://github.com/Todysheep/nonebot_plugin_bottle/assets/172282304/71ab4839-91ac-46df-8cf7-aa0ecea500ed">
还是报错怎么办QAQ

**Comment by LambdaYH** [comment]
第一张图的cooldown改成默认的{}，这个是使用中自动维护的

**Comment by Momoi-coder** [comment]
谢谢大佬QAQ，目前似乎暂时没问题了
