### ISSUE TITLE
能否使su在查看漂流瓶详情时显示更多的详细信息

### ISSUE THREAD

**Issue by aknyzsd** [Todysheep/nonebot_plugin_bottle#78]
根据群友反馈有人在漂流瓶里面塞磁链，想直接通过漂流瓶编号进行溯源发现漂流瓶详情中信息过少，只能通过搜索群名和群友名称去查找，有些麻烦qwq

**Comment by LambdaYH** [comment]
现在`漂流瓶详情`里应该挺多内容都有的。你是希望有哪些？

**Comment by aknyzsd** [comment]
怪了，我记得之前只有用户名称群名称回复和举报信息着，没有群号和QQ号着qwq
