### ISSUE TITLE
发送指令”扔漂流瓶“之后，发送图片报错SSL（已安装依赖）

### ISSUE THREAD

**Issue by nya520ww** [Todysheep/nonebot_plugin_bottle#84]
[漂流瓶.txt](https://github.com/user-attachments/files/18052249/default.txt)
![image](https://github.com/user-attachments/assets/dc4ea5e6-6f6e-4ede-a18b-df872320b010)

**Comment by LambdaYH** [comment]
似乎是httpx0.28.x会有的问题https://github.com/hbldh/pybankid/issues/74，如果可以的话，先把httpx回退到0.27.x

**Comment by nya520ww** [comment]
> 似乎是httpx0.28.x會有的問題 [hbldh/pybankid#74encode ](https://github.com/hbldh/pybankid/issues/74) [/httpx#3441](https://github.com/encode/httpx/issues/3441)
> 
> 如果可以的話，先把httpx退到0.27.x

谢谢佬，回退到0.27.0版本问题完美解决了
